[env:door-espnow-idf]
platform = espressif32
board = airm2m_core_esp32c3
framework = espidf
monitor_speed = 115200

; Flash DIO 模式 (合宙板外置 SPI Flash)
board_build.flash_mode = dio
board_build.flash_size = 4MB

; 关闭不需要的组件 (减小固件,加速编译)
build_flags =
