esphome:
  name: envpanel

# 选用带 8MB Flash + 8MB PSRAM 的 S3 板卡变体
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
  flash_size: 8MB

# WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "BMI160-ESP32S3"
    password: "12345678"

# HA API / OTA / Web
api:
ota:
  platform: esphome

time:
  - platform: homeassistant
    id: ha_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 22
        then:
          - logger.log: "Entering night deep sleep"
          - deep_sleep.enter:
              id: deep_sleep_control
              sleep_duration: 10h

deep_sleep:
  id: deep_sleep_control
# 建议用 USB CDC 日志（S3 很稳），串口则设定 baud_rate: 115200
logger:
  baud_rate: 0   # 0=禁用硬件串口日志，改用 USB CDC

web_server:
  port: 80
  auth:
    username: admin
    password: !secret wifi_password


# 引入显示（单独文件）
packages:
  display9341: !include display9341.yaml

# 添加传感器数据获取
sensor:
  # 从Home Assistant获取传感器数据 - 使用您提到的具体实体ID
  - platform: homeassistant
    name: "AHT20 Humidity"
    id: aht20_humidity
    entity_id: sensor.bmp_aht_esp32c3_aht20_humidity_2
    
  - platform: homeassistant
    name: "AHT20 Temperature" 
    id: aht20_temperature
    entity_id: sensor.bmp_aht_esp32c3_aht20_temperature_2

  # VOC传感器数据
  - platform: homeassistant
    name: "TVOC"
    id: voc_tvoc
    entity_id: sensor.voc_myesp32c3_tvoc
    unit_of_measurement: "mg/m³"
    
  - platform: homeassistant
    name: "甲醛"
    id: voc_hcho  
    entity_id: sensor.voc_myesp32c3_formaldehyde_ch_o
    unit_of_measurement: "mg/m³"
    
  - platform: homeassistant
    name: "CO2"
    id: voc_co2
    entity_id: sensor.voc_myesp32c3_co2
    unit_of_measurement: "mg/m³"

  # 天气预报数据
  - platform: homeassistant
    name: "室外温度"
    id: weather_temperature
    entity_id: weather.forecast_home
    attribute: temperature
    unit_of_measurement: "°C"
    
  - platform: homeassistant  
    name: "室外湿度"
    id: weather_humidity
    entity_id: weather.forecast_home
    attribute: humidity
    unit_of_measurement: "%"

# 添加天气状态文本传感器
text_sensor:
  - platform: homeassistant
    name: "天气状态"
    id: weather_condition
    entity_id: weather.forecast_home
