esphome:
  name: ld2402-esp32c3
  friendly_name: LD2402雷达人体感应传感器节点

esp32:
  board: airm2m_core_esp32c3
  framework:
    type: arduino

logger:
  level: DEBUG

api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# LD2402雷达传感器配置 - GPIO12直接读取
binary_sensor:
  # 人体存在检测 - GPIO12直接读取LD2402的高低电平
  - platform: gpio
    pin: 
      number: GPIO18
      mode: INPUT
    name: "人体存在"
    id: human_presence
    device_class: occupancy