esphome:
  name: door-opener-esp32c3
  friendly_name: "门锁控制器"
    
esp32:
  board: airm2m_core_esp32c3
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # 低功耗WiFi设置
  # power_save_mode: NONE  # 关闭省电模式，提高连接稳定性
  # # 快速连接，减少唤醒时间
  # fast_connect: false

api:

ota:
  platform: esphome

time:
  - platform: homeassistant
    id: ha_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - logger.log: "进入夜间深度睡眠"
          - deep_sleep.enter:
              id: deep_sleep_control
              sleep_duration: 8h

deep_sleep:
  id: deep_sleep_control


logger:
  level: DEBUG  # 提高到DEBUG级别，便于诊断问题
  logs:
    wifi: DEBUG
    api: DEBUG
    deep_sleep: INFO

# PWM输出配置
output:
  - platform: ledc
    id: door_servo_pwm
    pin: GPIO2            
    frequency: 100Hz

# 开门舵机控制配置
servo:
  - id: door_servo
    output: door_servo_pwm
    auto_detach_time: 2s    # 2秒后自动断开，确保开门动作完成
    min_level: 0%       
    max_level: 25%      

# 开门控制
number:
  - platform: template
    name: "mensuo_jiaodu"
    id: door_angle
    min_value: 0
    max_value: 180
    step: 1
    initial_value: 180  # 默认关门位置（180度）
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: door_servo
            level: !lambda 'return x / 180.0;'

# 自由角度设置器
  - platform: template
    name: "ziyou_jiaodu_shezhi"
    id: free_angle_control
    min_value: 0
    max_value: 180
    step: 5  # 5度步进，更精确控制
    initial_value: 90  # 默认中间位置
    optimistic: true
    icon: "mdi:rotate-orbit"
    set_action:
      then:
        - logger.log: "设置自由角度"
        - servo.write:
            id: door_servo
            level: !lambda 'return x / 180.0;'
        - number.set:
            id: door_angle
            value: !lambda 'return x;'

# 开门预设操作
button:
  - platform: template
    name: "kaimen_caozuo"
    id: door_open_btn
    icon: "mdi:door-open"
    on_press:
      then:
        - logger.log: "执行开门操作 - 设置到0度"
        - servo.write:
            id: door_servo
            level: 0.0  # 0度，完全开门
        - number.set:
            id: door_angle
            value: 0
        # 开门后等待3秒，然后自动关门
        - delay: 3s
        - logger.log: "自动关门 - 设置到180度"
        - servo.write:
            id: door_servo
            level: 1.0  # 180度，关门位置
        - number.set:
            id: door_angle
            value: 180
        - delay: 2s
        
  - platform: template
    name: "guanmen_caozuo"
    id: door_close_btn
    icon: "mdi:door-closed-lock"
    on_press:
      then:
        - logger.log: "执行关门操作 - 设置到180度"
        - servo.write:
            id: door_servo
            level: 1.0  # 180度，关门位置
        - number.set:
            id: door_angle
            value: 180
        - delay: 2s
        
  - platform: template
    name: "jiesuo_weizhi"
    id: door_unlock_btn
    icon: "mdi:lock-open"
    on_press:
      then:
        - logger.log: "移动到解锁位置 - 设置到0度"
        - servo.write:
            id: door_servo
            level: 0.0  
        - number.set:
            id: door_angle
            value: 0
        - delay: 2s

# 添加测试按钮用于调试舵机范围
  - platform: template
    name: "test_90_degree"
    id: test_90_btn
    on_press:
      then:
        - logger.log: "测试90度位置"
        - servo.write:
            id: door_servo
            level: 0.5  # 90度，中间位置
        - number.set:
            id: door_angle
            value: 90
        - number.set:
            id: free_angle_control
            value: 90

# 精确角度控制按钮
  - platform: template
    name: "jiaodu_30"
    id: angle_30_btn
    icon: "mdi:rotate-left"
    on_press:
      then:
        - logger.log: "设置30度"
        - servo.write:
            id: door_servo
            level: !lambda 'return 30.0 / 180.0;'
        - number.set:
            id: door_angle
            value: 30
        - number.set:
            id: free_angle_control
            value: 30
            
  - platform: template
    name: "jiaodu_60"
    id: angle_60_btn
    icon: "mdi:rotate-left"
    on_press:
      then:
        - logger.log: "设置60度"
        - servo.write:
            id: door_servo
            level: !lambda 'return 60.0 / 180.0;'
        - number.set:
            id: door_angle
            value: 60
        - number.set:
            id: free_angle_control
            value: 60
            
  - platform: template
    name: "jiaodu_120"
    id: angle_120_btn
    icon: "mdi:rotate-right"
    on_press:
      then:
        - logger.log: "设置120度"
        - servo.write:
            id: door_servo
            level: !lambda 'return 120.0 / 180.0;'
        - number.set:
            id: door_angle
            value: 120
        - number.set:
            id: free_angle_control
            value: 120
            
  - platform: template
    name: "jiaodu_150"
    id: angle_150_btn
    icon: "mdi:rotate-right"
    on_press:
      then:
        - logger.log: "设置150度"
        - servo.write:
            id: door_servo
            level: !lambda 'return 150.0 / 180.0;'
        - number.set:
            id: door_angle
            value: 150
        - number.set:
            id: free_angle_control
            value: 150

# 设备状态传感器
text_sensor:
  - platform: template
    name: "mensuo_shebei_zhuangtai"
    id: device_status
    update_interval: 60s  # 增加更新间隔，节省功耗
    lambda: |-
      auto time = id(ha_time).now();
      if (!time.is_valid()) return {"Time not synced"};

      int hour = time.hour;
      if (hour >= 0 && hour < 8) {
        return {"Night sleep mode"};
      } else {
        return {"Ready for door control"};
      }


# 电源和门锁状态传感器
sensor:
  - platform: template
    name: "yunxing_shijian"
    id: uptime_sensor
    unit_of_measurement: "s"
    update_interval: 30s
    lambda: 'return millis() / 1000.0;'
    
  - platform: template
    name: "mensuo_jiaodu_fankui"
    id: door_position_feedback
    unit_of_measurement: "°"
    update_interval: 5s
    lambda: 'return id(door_angle).state;'


# Web服务器 - 轻量级配置
web_server:
  port: 80



